Update chess.yml

diff --git a/.github/workflows/chess.yml b/.github/workflows/chess.yml
--- a/.github/workflows/chess.yml
+++ b/.github/workflows/chess.yml
@@ -77,7 +77,7 @@ jobs:
           # react to issue
           PAGER= gh api /repos/${{ github.repository }}/issues/${{ github.event.inputs.issue_number }}/reactions -f content='confused' | jq .
           # add comment
-          gh issue comment ${{ github.event.inputs.issue_number }} --body "@$(echo "$ISSUE" | jq -r .author) The game title or move was unable to be parsed."
+          gh issue comment ${{ github.event.inputs.issue_number }} --body "@$(echo "$ISSUE" | jq -r .author.login) The game title or move was unable to be parsed."
           # close issue
           gh issue close ${{ github.event.inputs.issue_number }}
           echo "INVALID The game title or move was unable to be parsed."
@@ -98,11 +98,11 @@ jobs:
         set -xe
         LAST_MOVER=$(cat $GAME_STAT_PATH | tail -n +2 | tail -n 1 | tac | awk -F'|' '{print $2)' | cut -c 2-)
         
-        if [[ $LAST_MOVER == "$(echo "$ISSUE" | jq -r .author)" ]]; then
+        if [[ $LAST_MOVER == "$(echo "$ISSUE" | jq -r .author.login)" ]]; then
           # react
           PAGER= gh api /repos/${{ github.repository }}/issues/${{ github.event.inputs.issue_number }}/reactions -f content='confused' | jq .
           # comment
-          gh issue comment ${{ github.event.inputs.issue_number }} --body "@$(echo "$ISSUE" | jq -r .author) Slow down! You _just_ moved, so can't immediately take the next turn. Invite a friend to take the next turn! [Share on Twitter...](https://twitter.com/share?text=I'm+playing+chess+on+a+GitHub+Profile+Readme!+I+just+moved.+You+have+the+next+move+at+https://github.com/${{ github.repository }})"
+          gh issue comment ${{ github.event.inputs.issue_number }} --body "@$(echo "$ISSUE" | jq -r .author.login) Slow down! You _just_ moved, so can't immediately take the next turn. Invite a friend to take the next turn! [Share on Twitter...](https://twitter.com/share?text=I'm+playing+chess+on+a+GitHub+Profile+Readme!+I+just+moved.+You+have+the+next+move+at+https://github.com/${{ github.repository }})"
           # close issue
           gh issue close ${{ github.event.inputs.issue_number }}
           echo "INVALID Same player making consecutive moves."
@@ -145,7 +145,7 @@ jobs:
           # react
           PAGER= gh api /repos/${{ github.repository }}/issues/${{ github.event.inputs.issue_number }}/reactions -f content='confused' | jq .
           # comment
-          gh issue comment ${{ github.event.inputs.issue_number }} --body "@$(echo "$ISSUE" | jq -r .author) The game data is corrupt. A new game will be booted in a moment."
+          gh issue comment ${{ github.event.inputs.issue_number }} --body "@$(echo "$ISSUE" | jq -r .author.login) The game data is corrupt. A new game will be booted in a moment."
           # close issue
           gh issue close ${{ github.event.inputs.issue_number }}
 
@@ -169,7 +169,7 @@ jobs:
         CHESS_NEW_GAME=false
         if [[ 
             # if new_game_request => new game
-            ( $CHESS_GAME_CMD == 'new' && '$(echo "$ISSUE" | jq -r .author)' == 'timburgan' ) ||
+            ( $CHESS_GAME_CMD == 'new' && '$(echo "$ISSUE" | jq -r .author.login)' == 'timburgan' ) ||
 
             ( $CHESS_GAME_CMD == 'new' && $CHESS_GAME_OVER == 'true' )
         ]]; then
@@ -183,7 +183,7 @@ jobs:
       run: |
         set -xe
         PAGER= gh api /repos/${{ github.repository }}/issues/${{ github.event.inputs.issue_number }}/reactions -f content='confused' | jq .
-        gh issue comment ${{ github.event.inputs.issue_number }} --body "@$(echo "$ISSUE" | jq -r .author) This is an invalid new game request. If a new game is genuinely needed, create a new issue and ping @timburgan."
+        gh issue comment ${{ github.event.inputs.issue_number }} --body "@$(echo "$ISSUE" | jq -r .author.login) This is an invalid new game request. If a new game is genuinely needed, create a new issue and ping @timburgan."
         gh issue close ${{ github.event.inputs.issue_number }}
         exit 1
 
@@ -206,7 +206,7 @@ jobs:
         PAGER= gh api /repos/${{ github.repository }}/issues/${{ github.event.inputs.issue_number }}/reactions -f content='rocket' | jq .
 
         # write stats
-        echo "new|@$(echo "$ISSUE" | jq -r .author)||${{ github.event.inputs.issue_number }}|$(date -Iseconds)" > $GAME_STAT_PATH
+        echo "new|@$(echo "$ISSUE" | jq -r .author.login)||${{ github.event.inputs.issue_number }}|$(date -Iseconds)" > $GAME_STAT_PATH
 
     - name: Load existing game and perform move
       if: ${{ env.CHESS_GAME_CMD == 'move' }}
@@ -228,7 +228,7 @@ jobs:
           # react to issue
           PAGER= gh api /repos/${{ github.repository }}/issues/${{ github.event.inputs.issue_number }}/reactions -f content='confused' | jq .
           # add comment
-          gh issue comment ${{ github.event.inputs.issue_number }} --body "@$(echo "$ISSUE" | jq -r .author) Whaaa.. '${CHESS_USER_MOVE}' is an invalid move! Usually this is because someone squeezed a move in just before you."
+          gh issue comment ${{ github.event.inputs.issue_number }} --body "@$(echo "$ISSUE" | jq -r .author.login) Whaaa.. '${CHESS_USER_MOVE}' is an invalid move! Usually this is because someone squeezed a move in just before you."
           # close issue
           gh issue close ${{ github.event.inputs.issue_number }}
           exit 0
@@ -236,18 +236,18 @@ jobs:
         EORUBY
 
         # write stats
-        echo "move|@$(echo "$ISSUE" | jq -r .author)|${CHESS_USER_MOVE}|${{ github.event.inputs.issue_number }}|$(date -Iseconds)" > $GAME_STAT_PATH
+        echo "move|@$(echo "$ISSUE" | jq -r .author.login)|${CHESS_USER_MOVE}|${{ github.event.inputs.issue_number }}|$(date -Iseconds)" > $GAME_STAT_PATH
 
         # write leaderboard
-        EXISTING_LINE=$(grep @$(echo "$ISSUE" | jq -r .author)$ $GAME_LEADERBOARD_PATH)
+        EXISTING_LINE=$(grep @$(echo "$ISSUE" | jq -r .author.login)$ $GAME_LEADERBOARD_PATH)
         if [[ -n "$EXISTING_LINE" ]]; then
           COUNT_OLD=$(echo $EXISTING_LINE | cut -d'|' -f1)
           COUNT_NEW=$(expr $COUNT_OLD + 1)
           WHO=$(echo $$EXISTING_LINE | cut -d'|' -f2)
-          sed -n '/@$(echo "$ISSUE" | jq -r .author)$/p' -i -- "s/$COUNT_OLD|$WHO/$COUNT_NEW|$WHO/g" $GAME_LEADERBOARD_PATH
+          sed -n '/@$(echo "$ISSUE" | jq -r .author.login)$/p' -i -- "s/$COUNT_OLD|$WHO/$COUNT_NEW|$WHO/g" $GAME_LEADERBOARD_PATH
           sort -t'|' -k1 -r $GAME_LEADERBOARD_PATH
         else
-          echo "1|@$(echo "$ISSUE" | jq -r .author)" >> $GAME_LEADERBOARD_PATH
+          echo "1|@$(echo "$ISSUE" | jq -r .author.login)" >> $GAME_LEADERBOARD_PATH
         fi
 
     - name: Update README
@@ -475,7 +475,7 @@ jobs:
     - name: Push PGN, README, stats, leaderboard changes
       run: |
         set -xe
-        git commit -am "@@$(echo "$ISSUE" | jq -r .author) $(echo "$ISSUE" | jq -r .title) via #${{ github.event.inputs.issue_number }}"
+        git commit -am "@@$(echo "$ISSUE" | jq -r .author.login) $(echo "$ISSUE" | jq -r .title) via #${{ github.event.inputs.issue_number }}"
         git push origin ${{ github.event.inputs.game_branch }}
 
     - name: Game over. Thank players
@@ -496,7 +496,7 @@ jobs:
         # move|dan|move|issue|date
         # move|joe|move|issue|date
         # move|dan|move|issue|date
-        # Move|$(echo "$ISSUE" | jq -r .author)|${CHESS_USER_MOVE}|${{ github.event.inputs.issue_number }}|$(date -Iseconds)
+        # Move|$(echo "$ISSUE" | jq -r .author.login)|${CHESS_USER_MOVE}|${{ github.event.inputs.issue_number }}|$(date -Iseconds)
         # EOF
 
         gh issue comment ${{ github.event.inputs.issue_number }} --body "That's game over! Thank you for playing that chess game. That game had ${STAT_MOVES} moves, $(echo "${STAT_PLAYERS}" | wc -l) players, and went for ${STAT_DURATION} hours. Let's play again at https://github.com/timburgan.\n\nPlayers that game: $(awk '{print;}' file.txt | paste -s -d', ')")
@@ -505,6 +505,6 @@ jobs:
       if: ${{ env.CHESS_GAME_CMD == 'move' }}
       run: |
         set -xe
-        gh issue comment ${{ github.event.inputs.issue_number }} --body "@$(echo "$ISSUE" | jq -r .author) Done. View back at https://github.com/${{ github.repository }}\n\nAsk a friend to take the next move: [Share on Twitter...](https://twitter.com/share?text=I'm+playing+chess+on+a+GitHub+Profile+Readme!+I+just+moved.+You+have+the+next+move+at+https://github.com/${{ github.repository }})")
+        gh issue comment ${{ github.event.inputs.issue_number }} --body "@$(echo "$ISSUE" | jq -r .author.login) Done. View back at https://github.com/${{ github.repository }}\n\nAsk a friend to take the next move: [Share on Twitter...](https://twitter.com/share?text=I'm+playing+chess+on+a+GitHub+Profile+Readme!+I+just+moved.+You+have+the+next+move+at+https://github.com/${{ github.repository }})")
         gh issue close ${{ github.event.inputs.issue_number }}
 
