Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -50,8 +50,13 @@ jobs:
 
           # game is valid - allow user to move
           rm -f issue_id
-          gh issue create --label "test" --title "$(cat tests/${{ matrix.scenario }}/issue-title.setup.txt)" --body '${{ github.ref }}' | awk -F'/' '{print $NF}' > issue_id
+          gh issue create --label "test" --title "$(cat tests/${{ matrix.scenario }}/issue-title.setup.txt)" --body "${{ github.ref }}" | awk -F'/' '{print $NF}' > issue_id
           
+          if [ ! -s issue_id ]; then
+            echo "FAILURE issue_id is empty"
+            exit 1
+          fi
+
           # reauth as GITHUB_TOKEN
           gh auth logout --hostname github.com
           echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
